FROM node:8

ENV HOME "/home/xpub"

RUN mkdir -p ${HOME}

WORKDIR ${HOME}

# Build yarn offline cache

RUN yarn config set yarn-offline-mirror /npm-packages-offline-cache && \
  yarn config set prefer-offline true && \
  yarn config set yarn-offline-mirror-pruning true

RUN git clone https://github.com/elifesciences/elife-xpub.git && \
    cd elife-xpub && \
    yarn autoclean --init && yarn && \
    cd && rm -rf elife-xpub

