FROM xpub/xpub:base

WORKDIR ${HOME}

COPY package.json yarn.lock app.js .babelrc .eslintignore .eslintrc .prettierrc .stylelintignore .stylelintrc ./
COPY static static
COPY api api
COPY webpack webpack
COPY config config
COPY app app

EXPOSE 3000

CMD []
