FROM node:8.14.0

ENV HOME "/home/xpub"

RUN mkdir -p ${HOME}

WORKDIR ${HOME}

COPY src/package.json src/yarn.lock ./
COPY src/client client
COPY src/packages packages

# We do a development install because react-styleguidist is a dev dependency and we want to run tests
# Remove cache and offline mirror in the same command, to avoid creating intermediate layers
RUN yarn install --frozen-lockfile \
    && yarn cache clean \
    && rm -rf /npm-packages-offline-cache

COPY \
    src/app.js \
    src/newrelic.js \
    src/.babelrc \
    src/.eslintignore \
    src/.eslintrc.js \
    src/.prettierrc \
    src/.stylelintignore \
    src/.stylelintrc \
    src/styleguide.config.js \
    ./

COPY src/app app
COPY src/config config
COPY src/scripts scripts
COPY src/styleguide styleguide
COPY src/test test
COPY src/webpack webpack
COPY src/templates templates

ENV NODE_ENV "production"
ENV XPUB_LOG_PATH "/var/log/xpub"
RUN mkdir -p ${XPUB_LOG_PATH}

RUN [ "npx", "pubsweet", "build"]

EXPOSE 3000

CMD []
