FROM node:8.14.0

ENV HOME "/home/xpub"

RUN mkdir -p ${HOME}

WORKDIR ${HOME}

COPY package.json yarn.lock ./
COPY client client
COPY packages packages

RUN yarn install

COPY \
    app.js \
    newrelic.js \
    .babelrc \
    .eslintignore \
    .eslintrc.js \
    .prettierrc \
    .stylelintignore \
    .stylelintrc \
    styleguide.config.js \
    ./

COPY app app
COPY config config
COPY scripts scripts
COPY styleguide styleguide
COPY test test
COPY webpack webpack
COPY templates templates

ENV NODE_ENV "production"
ARG CI_COMMIT_SHA
ENV CI_COMMIT_SHA ${CI_COMMIT_SHA}

ENV XPUB_LOG_PATH "/var/log/xpub"
RUN mkdir -p ${XPUB_LOG_PATH}

RUN [ "npx", "pubsweet", "build"]

EXPOSE 3000

CMD []
