FROM node:8.14.0

ENV HOME "/home/xpub"

RUN mkdir -p ${HOME}

WORKDIR ${HOME}

# install Chrome
RUN curl -sL http://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google.list
RUN apt-get update \
    && apt-get install -y google-chrome-stable socat \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY src/package.json yarn.lock ./
COPY src/client client
COPY src/packages packages

# We do a development install because react-styleguidist is a dev dependency and we want to run tests
# Remove cache and offline mirror in the same command, to avoid creating intermediate layers
RUN yarn install --frozen-lockfile \
    && yarn cache clean \
    && rm -rf /npm-packages-offline-cache

COPY \
    src/app.js \
    src/newrelic.js \
    src/.babelrc \
    src/.eslintignore \
    src/.eslintrc.js \
    src/.prettierrc \
    src/.stylelintignore \
    src/.stylelintrc \
    src/styleguide.config.js \
    ./

# Yes! we do need all this and the reason is that the browser tests use the config
# in turn the config relies on packages. 
# TODO: Fix the browser tests by passing in the "URL under test" as an env var

COPY src/app app
COPY src/config config
COPY src/scripts scripts
COPY src/styleguide styleguide
COPY src/test test
COPY src/webpack webpack
COPY src/templates templates

CMD []
