FROM xpub/xpub:20181213

WORKDIR ${HOME}

COPY package.json yarn.lock app.js .babelrc .eslintignore .eslintrc.js .prettierrc .stylelintignore .stylelintrc ./
COPY assets assets
COPY webpack webpack
COPY config config
COPY app app
COPY templates templates

ENV XPUB_LOG_PATH "/var/log/xpub"
RUN mkdir -p ${XPUB_LOG_PATH}

EXPOSE 3000

CMD []
