FROM node:8 as builder

RUN mkdir /build
WORKDIR /build

COPY package.json ./
COPY yarn.lock ./


COPY app.js .babelrc .eslintignore .eslintrc.js .prettierrc .stylelintignore .stylelintrc ./

COPY app app
COPY client client
COPY packages packages
COPY config config
COPY scripts scripts
COPY static static
COPY test test
COPY webpack webpack

# We do a development install because react-styleguidist is a dev dependency and we want to run tests
# Remove cache and offline mirror in the same command, to avoid creating intermediate layers
RUN yarn install --frozen-lockfile \
    && yarn cache clean \
    && rm -rf /npm-packages-offline-cache


# Need this to build the index.html and app.js
RUN npm run build

# Now remove all the packages used for build so we are ready for production
# NOTE: This is the section not fully working yet
RUN rm -rf node_modules
RUN yarn install --production
RUN du -h -d 2 node_modules | sort -h | tail

ENV NODE_ENV "production"
ARG CI_COMMIT_SHA
ENV CI_COMMIT_SHA ${CI_COMMIT_SHA}

FROM node:8-alpine
ENV NODE_ENV "production"
COPY --from=builder /build /elife-xpub
WORKDIR /elife-xpub

EXPOSE 3000
CMD ["node", "app.js"]
