FROM xpub/xpub:base

WORKDIR ${HOME}

COPY package.json yarn.lock app.js .babelrc .eslintignore .eslintrc .prettierrc .stylelintignore .stylelintrc ./
COPY static static
COPY webpack webpack
COPY config config
COPY app app
COPY templates templates

EXPOSE 3000

CMD []
