FROM node:8.14.0

ENV HOME "/home/xpub"

RUN mkdir -p ${HOME}

WORKDIR ${HOME}

# install Chrome
RUN curl -sL http://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google.list
RUN apt-get update \
    && apt-get install -y google-chrome-stable socat \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY package.json yarn.lock ./

RUN yarn install

COPY \
    app.js \
    newrelic.js \
    .babelrc \
    .eslintignore \
    .eslintrc.js \
    .prettierrc \
    .stylelintignore \
    .stylelintrc \
    styleguide.config.js \
    ./

COPY scripts scripts
COPY test test

RUN npx testcafe --version

CMD []
