export { default as App } from './app/App'
export { default as Dashboard } from './dashboard/Dashboard'
export { default as Login } from './login/Login'
export { default as AuthorDetailsPage } from './submission/AuthorDetailsPage'
export { default as FileUploadPage } from './submission/FileUploadPage'
