version: '3'
services:
  api-test:
    build: '.'
    image: 'elife-xpub_api-test'
    networks:
      - 'elife-xpub_default'
    environment:
      JWT_SECRET:

networks:
  elife-xpub_default:
    external:
      name: 'elife-xpub_default'
