#!/bin/bash

###
# ./mirror [DELAY] [SSH_KEY]
###

DELAY=${1:-60}
SSH_KEY=${2:-/root/.ssh/gitlab-mirror}

if ! ( [ -n "$TARGET" ] && [ -n "$MIRROR" ] ) ; then
  echo "TARGET and/or MIRROR missing"
  exit 1
fi

# Set up ssh and add a valid key
eval `ssh-agent -s`
ssh-add $SSH_KEY

# Clone the original repo and push to mirror
mkdir -p repo/
git clone --mirror $TARGET repo/
cd repo
git push --mirror $MIRROR

# Update the mirror
while true
do
git remote update --prune

# Start Gitlab's pull mirroring process
if [ -n "$GITLAB_PROJECT_ID" ] && [ -n "$GITLAB_PERSONAL_ACCESS_TOKEN" ] ; then
  curl --header "Private-Token: $GITLAB_PERSONAL_ACCESS_TOKEN" -X POST  "https://gitlab.com/api/v4/projects/$GITLAB_PROJECT_ID/mirror/pull/" && echo ""
fi

sleep $DELAY
done
